Created Data model
NalianAchei2020/RubyonRails-blog pull request #3
Opened 2024-01-11 15:11 UTC by NalianAchei2020

#  Acomplishment
- Connected to PostgreSQL database
- Created and run the necessary migration files.
- Table and column names match the ERD diagram.
- All columns that are foreign keys  have a corresponding index

2024-01-11 16:13 UTC, julie-ify reviewed
Hi @NalianAchei2020,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

* Your migrations are failing. You did not set up your migration files properly. You should create users table, followed by posts, then comments and likes. But since you created comments and likes before posts they raise errors for a new user setting up your app because comments and likes tables depend on posts table, which chronologically is not created until later.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2024-01-11 18:49 UTC, NalianAchei2020 commented
> Hi @NalianAchei2020,
> 
> While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> 
> ## Invalid Code Review Request
> * Your migrations are failing. You did not set up your migration files properly. You should create users table, followed by posts, then comments and likes. But since you created comments and likes before posts they raise errors for a new user setting up your app because comments and likes tables depend on posts table, which chronologically is not created until later.
> 
> Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _Invalid Code Review Request **does not count** into the code reviews limit._

2024-01-11 18:52 UTC, NalianAchei2020 commented
Hi @julie-ify 
From my commit history, I created it in the order you just mentioned. The post was created before comments and likes.

2024-01-11 20:12 UTC, mckent05 requested changes
Hi @NalianAchei2020, 

# STATUS: CHANGES REQUIRED ♻️ ♻️ 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![almost there](https://user-images.githubusercontent.com/73607512/207265056-d056ea78-77c5-4b66-802e-694a5ed4ecf3.gif)

## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👍 👍 
- Good job creating migration files to setup your database tables 👍 👍 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-11 20:12 UTC, mckent05 commented on db/migrate/20240111192555_create_posts.rb
> +      t.references :user, null: false, foreign_key: true
- You have done well so far, but as shown in the [ERD diagram](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_app_erd_v1_1.png), the column in the post table that references the user table should be named `author`. Please fix this 🙏.

```ruby
     t.references :author, foreign_key: { to_table: 'users' }
```

2024-01-12 05:39 UTC, TedLivist approved these changes
## STATUS: APPROVED ✔️ ✔️

Hi @NalianAchei2020,

✔️ Use of PostgreSQL for database

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-12 05:39 UTC, TedLivist commented on db/migrate/20240111192254_create_users.rb
> +      t.datetime :createdAt
- [ ] **[OPTIONAL]** I would suggest you remove these columns. Besides, the fact they do not follow snake case rule for table columns, there is no use for these `updateAt` and `createdAt` columns. The `t.timestamps` takes care of the `updated_at` and `created_at` columns that we need.

2024-01-12 05:39 UTC, TedLivist commented on db/migrate/20240111192555_create_posts.rb
> +      t.datetime :updatedAt
- [ ] **[OPTIONAL]** I would suggest you remove these columns. Besides, the fact they do not follow snake case rule for table columns, there is no use for these `updateAt` and `createdAt` columns. The `t.timestamps` takes care of the `updated_at` and `created_at` columns that we need.

2024-01-12 05:39 UTC, TedLivist commented on db/migrate/20240111192846_create_likes.rb
> +      t.datetime :updatedAt
- [ ] **[OPTIONAL]** I would suggest you remove these columns. Besides, the fact they do not follow snake case rule for table columns, there is no use for these `updateAt` and `createdAt` columns. The `t.timestamps` takes care of the `updated_at` and `created_at` columns that we need.

2024-01-12 05:39 UTC, TedLivist commented on db/migrate/20240111193049_create_comments.rb
> +      t.datetime :createdAt
- [ ] **[OPTIONAL]** I would suggest you remove these columns. Besides, the fact they do not follow snake case rule for table columns, there is no use for these `updateAt` and `createdAt` columns. The `t.timestamps` takes care of the `updated_at` and `created_at` columns that we need.

2024-01-12 13:23 UTC, merged